### ISSUE TITLE
Potential event leak - loadend before assets are loaded

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#12085]
Some events are not removed when disposing a scene before all assets are downloaded.

This is potentially a memory leak, as those events will trigger even after the scene was disposed, and as they could potentially reference the scene, they would keep the scene in memory. An example of a playground - #2AH4YH. To reproduce, dispose the scene right after creating it.

Stacktraces for the events registered (and not removed):

```
at XMLHttpRequest.EventTarget.addEventListener (__puppeteer_evaluation_script__:13:19)

      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/webRequest.ts:125:18)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:410:20)
      at retryLoop (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:448:8)
      at requestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:482:8)
      at RequestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:337:11)
      at LoadFile (webpack:/BABYLON/lts/core/generated/scene.ts:4374:24)
      at _loadFile (webpack:/BABYLON/lts/core/generated/Audio/sound.ts:284:52)
      at createScene (:40:33), <anonymous>:34:18)
      at eval (:40:33), <anonymous>:64:1)
      >>
      at XMLHttpRequest.EventTarget.addEventListener (__puppeteer_evaluation_script__:13:19)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/webRequest.ts:125:18)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:410:20)
      at retryLoop (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:448:8)
      at requestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:482:8)
      at RequestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:337:11)
      at LoadFile (webpack:/BABYLON/lts/core/generated/scene.ts:4374:24)
      at _loadFile (webpack:/BABYLON/lts/core/generated/Audio/sound.ts:284:52)
      at createScene (:40:33), <anonymous>:38:15)
      at eval (:40:33), <anonymous>:64:1)
      >>
      at XMLHttpRequest.EventTarget.addEventListener (__puppeteer_evaluation_script__:13:19)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/webRequest.ts:125:18)
      at addEventListener (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:410:20)
      at retryLoop (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:448:8)
      at requestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:482:8)
      at RequestFile (webpack:/BABYLON/lts/core/generated/Misc/fileTools.ts:337:11)
      at LoadFile (webpack:/BABYLON/lts/core/generated/scene.ts:4374:24)
      at _loadFile (webpack:/BABYLON/lts/core/generated/Audio/sound.ts:284:52)
      at createScene (:40:33), <anonymous>:42:15)
      at eval (:40:33), <anonymous>:64:1)
```

**Comment by deltakosh** [comment]
Not sure this one qualifies

The request will end at some point and release memory at that moment.

**Comment by deltakosh** [comment]
Wait.. no I found a way :)
