### ISSUE TITLE
NME: uploading a static cube texture in a Reflection block does not work

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#12423]
If in a `ReflectionTexture` block you try to upload a static cube texture (like `country.env` for eg), you get this error in the browser console log:

```
fileTools.ts:104 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Zt (fileTools.ts:104:15)
    at $t (fileTools.ts:160:15)
    at t.Ht._partialLoadImg (engine.cubeTexture.ts:303:5)
    at t.Ht._cascadeLoadImgs (engine.cubeTexture.ts:264:14)
    at t.Ht.createCubeTextureBase (engine.cubeTexture.ts:424:14)
    at t.Ht.createCubeTexture (engine.cubeTexture.ts:460:17)
    at t._loadTexture (cubeTexture.ts:374:52)
    at t.updateURL (cubeTexture.ts:291:18)
    at FileReader.o.onloadend (texturePropertyTabComponent.tsxx:130:50)
```

**Comment by deltakosh** [comment]
I'll have a look thanks!
