### ISSUE TITLE
Playground: we can't use a PBR material anymore with older Babylon versions

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Babylon.js#12435]
Try https://playground.babylonjs.com/#M6MLIN

If using any version other than "Latest" it will fail with:
```
TypeError: Cannot read properties of undefined (reading 'environmentBRDFTexture')
    at Function.e.GetEnvironmentBRDFTexture (babylon.js:16:1592073)
    at t [as constructor] (babylon.js:16:1782426)
    at new t (babylon.js:16:1816016)
    at createScene (<anonymous>:29:23)
    at window.initFunction (<anonymous>:51:16)
    at async O._compileAndRunAsync (rendererComponent.tsxx:313:17) 'Retrying if possible. If this error persists please notify the team.'
```

**Comment by RaananW** [comment]
Probably because of the missing "LastCreatedScene" feature. add "scene" to the constructor and it works:

https://playground.babylonjs.com/#M6MLIN#1

I'll let you close this if you think that's the issue

**Comment by Popov72** [comment]
Yes, I think that's ok to close the issue.
