### ISSUE TITLE
highlight does not work when the mesh is InstancedMesh

### ISSUE THREAD

**Issue by hefujie1988** [BabylonJS/Babylon.js#12543]
mesh.actionManager.registerAction(new ExecuteCodeAction(ActionManager.OnPointerOverTrigger, function () {
          _this.hl.addMesh(mesh, Color3.Green());
        }));

**Comment by hefujie1988** [comment]
error information:

core.js:6210 
        
    ERROR TypeError: Cannot read properties of undefined (reading 'add')
    at HighlightLayer.push.1hhk.HighlightLayer.addMesh (highlightLayer.js:434:1)
    at ExecuteCodeAction.func (app.component.ts:115:20)
    at ExecuteCodeAction.push.u8y2.ExecuteCodeAction.execute (directActions.js:406:1)
    at ExecuteCodeAction.push.bDcY.Action._executeCurrent (action.js:83:1)
    at ActionManager.push.ZXSw.ActionManager.processTrigger (actionManager.js:210:1)
    at InputManager.push.XdJO.InputManager.setPointerOverMesh (scene.inputManager.js:835:1)
    at Scene.push.tVVT.Scene.setPointerOverMesh (scene.js:4225:1)
    at InputManager.push.XdJO.InputManager._processPointerMove (scene.inputManager.js:173:1)
    at InputManager._onPointerMove (scene.inputManager.js:599:1)
    at Observer.callback (scene.inputManager.js:758:1)
