### ISSUE TITLE
Copy camera matrix to Omnitone Ambisonic audio rotation matrix 

### ISSUE THREAD

**Issue by gschian0** [BabylonJS/Babylon.js#12558]
I'm getting this error attempting to get the camera rotation 
using `https://googlechrome.github.io/omnitone/#home`
`omnitone.min.js:17 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.A.invertMatrix4 (omnitone.min.js:17:446)
    at z.setRotationMatrixFromCamera (omnitone.min.js:17:18117)
    at eval (Game.js:118:20)
    at e._renderLoop (babylon.js:16:98406)
A.invertMatrix4    @    omnitone.min.js:17
z.setRotationMatrixFromCamera    @    omnitone.min.js:17
eval    @    Game.js:118
e._renderLoop    @    babylon.js:16
requestAnimationFrame (async)        
e.QueueNewFrame    @    babylon.js:16
e._renderLoop    @    babylon.js:16
requestAnimationFrame (async)        
e.QueueNewFrame    @    babylon.js:16
e.runRenderLoop    @    babylon.js:16
doRender    @    Game.js:114
eval    @    index.js:10`

I would like to be able to rotate the camera view and have the audio mix rotation copy the camera rotation matrix... I'm hot sure how to translate these two types any help would be appreciated.

Bless,
-Gennaro

**Comment by deltakosh** [comment]
Hello as stated in the Github issue template, please use the forum for questions: forum.babylonjs.com

**Comment by gschian0** [comment]
Sorry about that.  🤙🏽🤙🏽🤙🏽
