### ISSUE TITLE
_checkForConnectedDevices throws in Chrome (sometimes)

### ISSUE THREAD

**Issue by daniel-rabe** [BabylonJS/Babylon.js#12824]
Sorry i could not reproduce the error but we see it in our Sentry logs often.

```
TypeError: Illegal invocation
  at _checkForConnectedDevices(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/DeviceInput/InputDevices/webDeviceInputSystem.js:177:38)
  at _enableEvents(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/DeviceInput/InputDevices/webDeviceInputSystem.js:143:18)
  at new e(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/DeviceInput/InputDevices/webDeviceInputSystem.js:36:14)
  at new e(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/DeviceInput/InputDevices/internalDeviceSourceManager.js:50:39)
  at new e(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/DeviceInput/InputDevices/deviceSourceManager.js:15:49)
  at attachControl(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/Inputs/scene.inputManager.js:435:37)
  at attachControl(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/scene.js:1522:28)
  at new t(webpack://egr-onlineplanner/./node_modules/@babylonjs/core/scene.js:665:19)
```

Browser: only in chrome (different versions 79, 80, 96, 97, 98)

OS: Windows 10

Maybe someone can give me a hint would could cause it.

**Comment by RaananW** [comment]
We will be happy to help in our forum, https://forum.babylonjs.com (just as the issue template has suggested). Closing and looking forward to talking to you there.

**Comment by daniel-rabe** [comment]
ok thanks https://forum.babylonjs.com/t/checkforconnecteddevices-throw-typeerror-illegal-invocation/32722
