### ISSUE TITLE
Breakage in 3.2.0-beta.2 and beyond

### ISSUE THREAD

**Issue by chase-moskal** [BabylonJS/Babylon.js#4344]
first, i must confess my unbridled love for babylon js -- it's so wonderful that top developers are putting their heads together to create open source software which empowers indie developers like me to create rich experiences on the web that would be impossible otherwise -- nothing else out there comes close to babylon -- so thank you!

i attempted to upgrade babylon from 3.2.0-beta.1, and it's broken my build

starting from [my monarch games project](https://github.com/monarch-games/engine), commit 3346909514e6f5d30fcb61342afc4139e10d387e -- below are the results of some testing i've done to help diagnose this

i wonder what could be causing these problems?

## using typescript 2.7.2

- **`npm install babylonjs@3.2.0-beta.1 && npm install`**  
  build succeeds  
  ```
  done production build
  ```

- **`npm install babylonjs@3.2.0-beta.2 && npm install`**  
  build fails, no idea what 'earcut' is  
  ```
  Error: Cannot find module 'earcut' from 'F:\projects\monarch-games\engine\node_modules\babylonjs'
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
  ```

- **`npm install babylonjs@3.2.0 && npm install`**  
  build fails looking for 'oimo'  
  ```
  Error: Cannot find module 'oimo' from 'F:\projects\monarch-games\engine\node_modules\babylonjs'
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
  ```

- **`npm install babylonjs@3.3.0-alpha.2 && npm install`**  
  build fails looking for 'oimo'  
  ```
  Error: Cannot find module 'oimo' from 'F:\projects\monarch-games\engine\node_modules\babylonjs'
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
  ```

## using typescript 2.8.3

- **`npm install typescript@2.8.3 babylonjs@3.2.0-beta.1 && npm install`**  
  build fails with d.ts errors  
  ```
  node_modules/babylonjs/babylon.d.ts(263,5): error TS2717: Subsequent property declarations must have the same type.  Property 'getVRDisplays' must be of type '() => Promise<VRDisplay[]>', but here has type '() => any'.
  node_modules/babylonjs/babylon.d.ts(284,5): error TS2687: All declarations of 'hasOrientation' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(285,5): error TS2687: All declarations of 'hasPosition' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(286,5): error TS2687: All declarations of 'position' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(287,5): error TS2687: All declarations of 'linearVelocity' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(288,5): error TS2687: All declarations of 'linearAcceleration' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(289,5): error TS2687: All declarations of 'orientation' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(290,5): error TS2687: All declarations of 'angularVelocity' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(291,5): error TS2687: All declarations of 'angularAcceleration' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(23429,108): error TS2304: Cannot find name 'MSBaseReader'.
  node_modules/babylonjs/babylon.d.ts(23430,100): error TS2304: Cannot find name 'MSBaseReader'.
  node_modules/babylonjs/babylon.d.ts(24432,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'VRDisplay' must be of type '{ new (): VRDisplay; prototype: VRDisplay; }', but here has type 'any'.
  node_modules/babylonjs/babylon.d.ts(24433,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'VRFrameData' must be of type '{ new (): VRFrameData; prototype: VRFrameData; }', but here has type 'any'.
  node_modules/typescript/lib/lib.dom.d.ts(4878,14): error TS2687: All declarations of 'angularAcceleration' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4879,14): error TS2687: All declarations of 'angularVelocity' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4880,14): error TS2687: All declarations of 'hasOrientation' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4881,14): error TS2687: All declarations of 'hasPosition' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4882,14): error TS2687: All declarations of 'linearAcceleration' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4883,14): error TS2687: All declarations of 'linearVelocity' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4884,14): error TS2687: All declarations of 'orientation' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4885,14): error TS2687: All declarations of 'position' must have identical modifiers
  ```

- **`npm install typescript@2.8.3 babylonjs@3.2.0-beta.2 && npm install`**  
  build fails with d.ts errors  
  ```
  node_modules/babylonjs/babylon.d.ts(283,5): error TS2687: All declarations of 'hasOrientation' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(284,5): error TS2687: All declarations of 'hasPosition' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(285,5): error TS2687: All declarations of 'position' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(286,5): error TS2687: All declarations of 'linearVelocity' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(287,5): error TS2687: All declarations of 'linearAcceleration' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(288,5): error TS2687: All declarations of 'orientation' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(289,5): error TS2687: All declarations of 'angularVelocity' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(290,5): error TS2687: All declarations of 'angularAcceleration' must have identical modifiers.
  node_modules/babylonjs/babylon.d.ts(23876,108): error TS2304: Cannot find name 'MSBaseReader'.
  node_modules/babylonjs/babylon.d.ts(23877,100): error TS2304: Cannot find name 'MSBaseReader'.
  node_modules/babylonjs/babylon.d.ts(25108,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'VRFrameData' must be of type '{ new (): VRFrameData; prototype: VRFrameData; }', but here has type 'any'.
  node_modules/typescript/lib/lib.dom.d.ts(4878,14): error TS2687: All declarations of 'angularAcceleration' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4879,14): error TS2687: All declarations of 'angularVelocity' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4880,14): error TS2687: All declarations of 'hasOrientation' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4881,14): error TS2687: All declarations of 'hasPosition' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4882,14): error TS2687: All declarations of 'linearAcceleration' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4883,14): error TS2687: All declarations of 'linearVelocity' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4884,14): error TS2687: All declarations of 'orientation' must have identical modifiers.
  node_modules/typescript/lib/lib.dom.d.ts(4885,14): error TS2687: All declarations of 'position' must have identical modifiers.
  ```

- **`npm install typescript@2.8.3 babylonjs@3.2.0 && npm install`**  
  build fails looking for 'cannon'  
  ```
  Error: Cannot find module 'cannon' from 'F:\projects\monarch-games\engine\node_modules\babylonjs'
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
  ```

- **`npm install typescript@2.8.3 babylonjs@3.2.0-alpha.2 && npm install`**  
  build fails looking for 'earcut'  
  ```
  Error: Cannot find module 'earcut' from 'F:\projects\monarch-games\engine\node_modules\babylonjs'
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at F:\projects\monarch-games\engine\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
  ```

**Comment by deltakosh** [comment]
Hello:)
you are not on latest release (We are now on 3.2 release and 3.3-alpha2)

Regarding oimo, cannon and earcut: they are now dependencies of bjs package

**Comment by RaananW** [comment]
See here for further information regarding external dependencies - http://doc.babylonjs.com/features/npm_support#external-libraries

**Comment by chase-moskal** [comment]
@deltakosh, @RaananW — ahah, that's the ticket! thanks fellas!

this worked for me:

**`npm install typescript@2.8.3 babylonjs@3.2.0 earcut@2.1.3 cannon@0.6.2 oimo@1.0.9 && npm install`**

**Comment by RaananW** [comment]
awesome! we hope the unbridled love will forever stay :smile:

**Comment by deltakosh** [comment]
Can't agree more!

**Comment by chase-moskal** [comment]
you can be sure of it, this is only the beginning!
