### ISSUE TITLE
3dsmax exporter throwing exceptions.

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Babylon.js#460]
I recently installed the 3dsmax exporter to my `bin/assemblies` directory. I'm on **windows 7** with **3dsmax 2013**. **.NET 4.0** I'm now seeing some errors.

On Startup:
```
System.TypeLoadException: Could not load type
'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

When I click the `Babylon File Exporter...` button
```
System.TypeLoadException: Could not load type
'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr*
typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32
methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[]
methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32
methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[]
methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord
caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
   at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
   at System.Reflection.CustomAttributeData.GetCustomAttributes(Assembly target)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation& fallbackLocation)
   at System.Resources.ResourceManager.CommonSatelliteAssemblyInit()
   at System.Resources.ResourceManager..ctor(Type resourceSource)
   at System.ComponentModel.ComponentResourceManager..ctor(Type t)
```

**Comment by kevzettler** [comment]
@deltakosh Why was this closed with no comment or follow up? this is still an issue. If you think otherwise I'd like an explanation.

**Comment by deltakosh** [comment]
Sorry I misclicked. This is a unable to repro issue
I tested on two differents PC with same congi and no luck to see the issue

**Comment by RaananW** [comment]
I know this is closed, but for future reference - Async was introduced in .NET 4.5, try upgrading your version and see if it works. See here - https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.iasyncstatemachine%28v=vs.110%29.aspx

**Comment by kevzettler** [comment]
@RaananW Thanks so much for the follow up! For future visitors upgrading to .NET 4.5 resolved this.
