### ISSUE TITLE
AssetsManager doesn't work with NullEngine

### ISSUE THREAD

**Issue by proace137** [BabylonJS/Babylon.js#4626]
The AssetManager class is trying to use the window object which dont work in a node environment.

I even used "engine.hideLoadingUI();" but it still accesses the window object.
I use the assetManager.addMeshTask function to load my meshes but I get the following error:

> BJS - [04:17:33]: Babylon.js null engine (v3.2.0) launched
Server started on port 8999
BJS - [04:17:33]: Error running progress callbacks.
ReferenceError: window is not defined
    at Function.t.SetImmediate (mypath\node_modules\babylonjs\babylon.js:3:28552)
    at i._decreaseWaitingTasksCount (mypath\node_modules\babylonjs\babylon.js:50:4374)
    at i (mypath\node_modules\babylonjs\babylon.js:50:5126)
    at i.e.onDoneCallback (mypath\node_modules\babylonjs\babylon.js:50:279)
    at mypath\node_modules\babylonjs\babylon.js:49:31907
    at mypath\node_modules\babylonjs\babylon.js:50:872
    at p (mypath\node_modules\babylonjs\babylon.js:35:14889)
    at mypath\node_modules\babylonjs\babylon.js:35:15232
    at m (mypath\node_modules\babylonjs\babylon.js:35:13214)
    at XMLHttpRequest.p (mypath\node_modules\babylonjs\babylon.js:4:2941)

**Comment by deltakosh** [comment]
Good catch 
I'll fix that asap

**Comment by deltakosh** [comment]
Can you tell me what is inside your onProgress or onProgressObservable code?

**Comment by deltakosh** [comment]
Let's try with this change
Please reopen if the fix is not confirmed
