### ISSUE TITLE
[Gulp - bug] Can't use typescript-all and run commands with gulp 

### ISSUE THREAD

**Issue by Bloadrick** [BabylonJS/Babylon.js#4795]
Hi,

I can't get the command Gulp typescript-all and run to work.
When I try it throw this error : 

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Developpement\Babylon.js-130718\gui\webpack.config.js:2:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at D:\Developpement\Babylon.js-130718\tools\gulp\gulpfile.js:666:32
    at Array.map (<anonymous>)
    at D:\Developpement\Babylon.js-130718\tools\gulp\gulpfile.js:662:34
    at Array.map (<anonymous>)

I think it's about the GUI so it might be related to this : https://github.com/BabylonJS/Babylon.js/issues/4776

**Comment by RaananW** [comment]
is this after a successful npm install?

**Comment by Bloadrick** [comment]
Ok I have run a npm install and it's working now thank you ! 

Weird I have not thought about that, I'm closing this issue.
