### ISSUE TITLE
new entry points for Grid

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#5303]
* grid.columnCount
* grid.rowCount
* grid.getChildAt(row, col)

**Comment by deltakosh** [comment]
Sure thing:)

**Comment by deltakosh** [comment]
I can't assign it to you through github but consider it yours.
Thanks for your help

**Comment by deltakosh** [comment]
Up?

**Comment by Nodragem** [comment]
I was on it!

**Comment by Nodragem** [comment]
I did not succeed to get gulp to compile Babylon.js as explained here:
https://github.com/BabylonJS/Babylon.js/tree/master/Tools/Gulp

I went in the folder `Tools/Gulp` and then I ran:
```
gulp typescript
```
And I get:

```
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-uglify'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Creation\Gamedev\BabylonJS\Babylon.js\Tools\Gulp\gulpfile.js:2:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I will have another try tomorrow.

**Comment by deltakosh** [comment]
Make sure to install gulp@4.0.0
By the way I did it because you told me about your new job :)

**Comment by Nodragem** [comment]
yeah :/ my bad, I should have let you know I was on it.
I will still try to get my compilation working so that I am ready to contribute :D

**Comment by deltakosh** [comment]
Sounds good
