### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by liudonghua123** [BabylonJS/Babylon.js#9255]
I just cloned the repo and want to build a sandbox, I use the latest node on windows. And when I execute `npm install`, I got `unable to resolve dependency tree` errors. I found the dependence `awesome-typescript-loader` (https://github.com/BabylonJS/Babylon.js/blob/master/package.json#L53, https://github.com/s-panferov/awesome-typescript-loader/blob/v5.2.1/package.json#L46) was conflict with `typescript` (https://github.com/BabylonJS/Babylon.js/blob/master/package.json#L107). The following is the full logs.

```shell
D:\code\js\Babylon.js>npm i --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.0.3
npm info using node@v15.0.1
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:D:\code\js\Babylon.js\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\Liu.D.H\.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:C:\Users\Liu.D.H\AppData\Roaming\npm\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 1ms
npm timing config:load:setEnvs Completed in 2ms
npm timing config:load Completed in 15ms
npm verb npm-session 6785d444f07f9540
npm timing npm:load Completed in 49ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 25ms
npm timing idealTree:userRequests Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/@fortawesome%2ffontawesome-svg-core 1482ms
npm http fetch GET 200 https://registry.npmjs.org/@fortawesome%2ffree-regular-svg-icons 670ms
npm http fetch GET 200 https://registry.npmjs.org/@fortawesome%2ffree-solid-svg-icons 1363ms
npm http fetch GET 200 https://registry.npmjs.org/@fortawesome%2freact-fontawesome 890ms
npm http fetch GET 200 https://registry.npmjs.org/react 1126ms
npm http fetch GET 200 https://registry.npmjs.org/@svgr%2fwebpack 572ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fchai 831ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fdagre 315ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fmocha 328ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 2300ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2freact 894ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2freact-color 345ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2freact-dom 594ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fsinon 839ms
npm http fetch GET 200 https://registry.npmjs.org/ajv 878ms
npm http fetch GET 200 https://registry.npmjs.org/awesome-typescript-loader 861ms
npm http fetch GET 200 https://registry.npmjs.org/typescript 5591ms
npm timing idealTree Completed in 20049ms
npm timing command:install Completed in 20063ms
npm verb stack Error: unable to resolve dependency tree
npm verb stack     at Arborist.[failPeerConflict] (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1011:25)
npm verb stack     at Arborist.[loadPeerSet] (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:991:36)
npm verb stack     at async Arborist.[buildDepStep] (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:760:11)
npm verb stack     at async Arborist.buildIdealTree (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:202:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:121:5)
npm verb stack     at async install (C:\Users\Liu.D.H\AppData\Roaming\nvm\v15.0.1\node_modules\npm\lib\install.js:40:5)     
npm verb cwd D:\code\js\Babylon.js
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose"
npm verb node v15.0.1
npm verb npm  v7.0.3
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: babylonjs@4.2.0-beta.17
npm ERR! Found: typescript@4.0.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   dev awesome-typescript-loader@"^5.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Liu.D.H\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm verb exit 1
npm timing npm Completed in 21038ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Liu.D.H\AppData\Local\npm-cache\_logs\2020-10-23T06_30_03_972Z-debug.log

D:\code\js\Babylon.js>
```

**Comment by liudonghua123** [comment]
I can make `npm install` to work via adding `--legacy-peer-deps` command arguments. However I saw `awesome-typescript-loader` (https://github.com/s-panferov/awesome-typescript-loader) was achieved and inactive, maybe we should switch to another dependence like `ts-loader` (https://github.com/TypeStrong/ts-loader).

**Comment by sebavan** [comment]
Please as the issue template explain, use the forum first before creating issues on github.

How to locally build is covered in here : https://doc.babylonjs.com/how_to/how_to_start
